//! Raw FFI bindings to [dxil-spirv](https://github.com/HansKristian-Work/dxil-spirv).
//!
//! This crate is generated by bindgen from `dxil_spirv_c.h` and links the
//! statically-built `dxil-spirv-c-static` CMake target. Most users should
//! prefer the safe `dxil-spirv` crate instead of using these bindings directly.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
